OpenTechFund/hypha

opentech/apply/users/middleware.py, opentech/apply/users/templates/users/account.html, opentech/apply/users/templates/users/login.html, opentech/apply/users/tests/test_oauth_access.py, opentech/settings/base.py
Displays error messages on the login form (including those from django social auth) and hides "Manage OAuth" for the time being
=> OAuth tweaks

opentech/apply/funds/admin.py, opentech/apply/funds/templates/funds/admin/parent_chooser.html
As requested in the review of feature 34, makes the parent chooser page more in keeping with funds/rounds.
=> Add a view and form for the fund chooser page

opentech/public/funds/templates/public_funds/includes/project_listing.html, opentech/public/funds/templates/public_funds/lab_page.html, opentech/public/projects/templates/projects/project_page.html, opentech/public/utils/templates/utils/includes/media_box_icon.html, opentech/static_src/src/sass/components/_media-box.scss
refactoring media boxes so the large image is used as a background image, rather than an image tag, therefore eliminating the image wobble on hover and the need for an extra img tag
=> refactoring media boxes

opentech/public/search/views.py
Hides the fund forms and the round pages
@chris-lawton Should fix the issue we had the other day.
=> Limit the search to only pages on the public site

opentech/apply/funds/models.py, opentech/apply/funds/tests/test_models.py
Fixes a 500 that was happening on staging. When a fund exists but no rounds have ever been created this would cause an error. 
I've returned None as that is a valid response for the end date. This is mainly used when rendering the deadline onto listing items. You need to combine `next_deadline` with `is_open` to confirm that there is a round someone can apply for.
=> Prevent errors when there is no round defined for a fund

opentech/public/funds/templates/public_funds/blocks/related_reviewers.html, opentech/public/funds/templates/public_funds/includes/reviewer_listing.html, opentech/static_src/src/sass/public/components/_media-box.scss
Front end work for the reviewers block used on the fund page.
Changed from using the `person_listing.html` partial as this is used on the person index page.
=> adding reviewers block template and corresponding styles

opentech/apply/funds/differ.py
Checked against various diffs. Doesn't seem to have an impact on style for large diffs, but improves the look of small diffs, especially in the required fields area.
=> Wrap diffs in span

opentech/apply/users/templates/users/activation/email.txt, opentech/apply/users/templates/users/activation/email_subject.txt, opentech/apply/users/tests/test_utils.py, opentech/apply/users/utils.py
Django was using the `b''` identifier in the url, hence the `&#39` we were seeing the urls for activation. `decode()` the bytes back to a string resolves the issue.
=> Fix the issue with bytes in urls

opentech/apply/funds/templates/funds/includes/field.html
will impact rendering of django password validators and admin input only so
considered reasonably safe.
=> Mark the help text as safe

opentech/settings/base.py
Our user model uses email and doesnt have an username field
=> Remove the username step from the social auth

opentech/apply/determinations/views.py, opentech/apply/funds/models/mixins.py, opentech/apply/funds/models/submissions.py, opentech/apply/funds/tests/test_views.py, opentech/apply/funds/views.py
This allows us to skip the file handling if we are just updating the status field. Should avoid some of the issues we've been seeing on sending determinations.
=> Short circuit the save for the transition

opentech/apply/funds/tests/test_models.py
attempting solution for #543 
Just adding a test, no behaviour change.
Will add more discussion onto the page.
=> Ensure we don't change the user's name on submission

opentech/apply/users/templates/users/password_reset/email.txt, opentech/apply/users/tests/test_views.py
This should now correctly pick up the site from the request's origin. Which will always be the apply site.
closes #539
=> Make sure the reset url is the correct site from the request

.travis.yml, opentech/apply/funds/models/mixins.py, setup.cfg
Travis seems to have updated its version of pycodestyle and added new checks. Adding them to ”ignore” in setup.cfg.
Also removed one unused variable ”e” in mixins.py.
=> Make flake8 work again on travisci.

opentech/settings/base.py
This will allow us to set a custom STAFF_EMAIL_DOMAINS for the sandbox site. Since it will default to opentech.fund no changes are needed on the sites.
=> Allow STAFF_EMAIL_DOMAINS to be set as env var. Default to original value.

opentech/apply/funds/models/mixins.py, opentech/apply/funds/tests/test_models.py
This fixes the issue with applications not showing any submission information. 
This was due to the deserialisation method falling over if it found a missing named block, essentially returning `None` for all responses. (`value` from the look of the live data).
This allows the data to correctly fail silently if a named block is submitted without a value.
A separate question for OTF is whether the value should be not required for the round causing the issues.
=> Allow non responded named fields to be rendered

opentech/settings/dev.py
- Adds `lvh.me` and `apply.lvh.me` domains to `ALLOWED_HOSTS` 
Browsers other than Chrome won't handle `*.localhost` subdomains without modifying hosts files - when browser testing this isn't practical so the addition of these domains will remedy this.
=> adds lvh.me domains to allowed hosts

opentech/apply/funds/models/submissions.py
this fixes the sentry issue found here: https://sentry.io/otf/otf-webapp-test/issues/844604394/
The query was generating too many references to form_data and getting confused. This makes the table to use explicit.
Most likely impacted the testing of #791
=> Make sure that we can get the distinct column for the jsonfield

opentech/apply/urls.py, opentech/apply/utils/__init__.py, opentech/apply/utils/app.py, opentech/apply/utils/templates/apply/404.html, opentech/apply/utils/views.py, opentech/public/mailchimp/templates/mailchimp/newsletter_signup.html, opentech/public/search/views.py, opentech/settings/base.py, opentech/templates/base.html, opentech/urls.py
@emullaney Testing highlighted this issue where `/search/` from the public site was appearing on the apply site.
~~I've tweaked the url conf to prevent this.~~
Change of plan. I've 404'ed the search view on apply and directing all uses of serach and newsletter to the public site. I've also made a custom 404 for the apply site which varies the base template based on if you are logged in or not.
We use two URL confs. One for each of the apply and public. They are essentially the same base urls, but it allows us to resolve login urls on the public site and removes all apply urls from the public site.
This is handled in middleware based on the host name of the site being the apply site as configured in the Wagtail admin.
=> Remove the public search and newsletter urls from the apply site

opentech/static_src/src/app/src/api/utils.js
adds credentials to fetch so the cookie is set in the headers and the fetch works successfully in safari
=> ensure fetch works in safari

opentech/static_src/src/app/src/components/DetailView/style.scss
make the detail view scrollbars appear as an overlay so it doesn't affect the width of the content
=> overlay scroll bars in detail view

opentech/static_src/src/javascript/apply/submission-filters.js
@chris-lawton 
This means that the filters show correctly whenever any filter is selected that isn't `query` or `sort`
=> any filters not in list should cause filters to show

opentech/apply/users/templates/users/password_reset/confirm.html
The password reset form was not displaying any errors making it hard for users to understand why the form did not submit.
<strike>When a user access a valid activation url their account are directly set to active and they are logged in. They are then redirected to a form where they should set a password.
For some reason many users simply skip this step and they end up with an active account with no password. Accounts with no password can not use the password reset form.
By using the "set_unusable_password()" to set a password in the first step users can at least use the password reset form if they skip creating a password for their account upon activation.
I have now set an unusable password on all active accounts with empty password as well.</strike>
~~~~
from django.contrib.auth import …
=> Display errors and password rules on password reset form

opentech/apply/funds/api_views.py, opentech/apply/funds/permissions.py, opentech/apply/funds/serializers.py, opentech/apply/funds/urls.py, opentech/settings/base.py, requirements.txt
link #768 
Initial work: DRF integration (like default authentication), staff permissions and submissions list endpoint.
Example endpoint: `/apply/api/submissions/`. Normal submissions URL is `/apply/submissions/`. It seems better to contain API endpoints under `***/api/***`.
=> WIP: API spec implementation

opentech/apply/funds/views.py
make sure we can order the table on the summary overview page without impacting other things that use that data.
@gibbsmaya Partial fix of the issue #915
=> Correctly limit the table data without affecting activity

requirements.txt
@frjo 
It looks like the changes to the python version have triggered an issue with django/redis compatibility.
django-redis 4.10.0 works correctly with redis 3.0
=> upgrade to redis 3.0 compatible django redis

opentech/apply/dashboard/templates/dashboard/dashboard.html, opentech/apply/dashboard/views.py, opentech/apply/funds/models/applications.py, opentech/apply/funds/templates/funds/includes/round-block.html, opentech/apply/funds/templates/funds/submissions.html, opentech/apply/funds/tests/models/test_roundsandlabs.py, opentech/apply/funds/views.py
- Block is title "Your rounds and labs"
- Only displayed for OTF staff where user is the 'Round lead' (does not display for other user types)
- If no Round/Labs then block does not display (this was done on #822 and copied here)
- Unit test for `by_lead` filter method
=> Feature/810: Rounds block: Dashboard changes

opentech/apply/funds/models/mixins.py, opentech/apply/funds/views.py
Link #749 
@frjo The compare revisions code currently create comparisons by checking the diff in rendered HTML. Therefore when a submission has an attachment it compares only the output HTML of the file field, not the actual file. Comparing HTML generates broken HTML for file like 
```html
<a class="link link--download" href="/media/submission/5/9702febd-53c6-4999-82f8-1cdedbe78f1f/<span class="diff diff__added">contracts_cQrOe9H.csv">
<div></span><span class="diff diff__deleted">test_document.docx">
<div></span>
```
Revisions compare [code](https://github.com/OpenTechFund/opentech.fund/blob/master/opentech/apply/funds/differ.py#L22) need updates to handle non-text answers like an image and also display their differences. Images changes can show an old image and a new image. We currently …
=> Exclude non-text answers like attachment from compare revisions

opentech/public/forms/wagtail_hooks.py
Link #947 
Hide none wagtail forms from `/admin/forms/`
=> Forms section only display wagtail forms not apply

opentech/static_src/src/app/src/SubmissionsByRoundApp.js, opentech/static_src/src/app/src/SubmissionsByStatusApp.js, opentech/static_src/src/app/src/containers/ByRoundListing.js, opentech/static_src/src/app/src/containers/ByStatusListing.js, opentech/static_src/src/app/src/containers/GroupByRoundDetailView.js, opentech/static_src/src/app/src/containers/GroupByStatusDetailView.js, opentech/static_src/src/app/src/redux/actions/submissions.js, opentech/static_src/src/app/src/redux/reducers/index.js, opentech/static_src/src/app/src/redux/reducers/statuses.js, opentech/static_src/src/app/src/redux/reducers/submissions.js, opentech/static_src/src/app/src/redux/selectors/statuses.js, opentech/static_src/src/app/src/redux/selectors/submissions.js
@tm-kn this makes the statuses be more like the round - we set a current set of statuses and then refer to that elsewhere.
It removes the passing around of the statuses within the components.
I've also split out the selectors into multiple files to be more explicit and reduce confusion.
=> Fixup the behaviour with status

opentech/static_src/src/app/src/components/SubmissionLink/index.js, opentech/static_src/src/app/src/components/SubmissionLink/styles.scss, opentech/static_src/src/app/src/containers/DisplayPanel/index.js
moves the open in a new submission link into the status tab to prevent it taking up space in the dom and mis-calculating the page height
=> move open submission in a new tab link to the status tab

opentech/apply/funds/serializers.py, opentech/static_src/src/app/src/components/ReviewBlock/styles.scss, opentech/static_src/src/app/src/components/SidebarBlock/index.js, opentech/static_src/src/app/src/components/SidebarBlock/styles.scss, opentech/static_src/src/app/src/containers/DisplayPanel/index.js, opentech/static_src/src/app/src/containers/ReviewInformation.js, opentech/static_src/src/app/src/containers/ScreeningOutcome.js, opentech/static_src/src/app/src/containers/StatusActions.js
This includes the screening status within the status tab of the detail view.
=> GH-1077: Add screening to status tab

opentech/apply/funds/models/mixins.py
It seems single field field has a long standing bug. Not noticed since now one have used them until resently. Multi file fields works well.
Users can submit forms with single field fields but they can't be edited if they are empty.
This pr add a check for empire field fields and set the value to an empty list.
=> Handle empty single field field.

opentech/apply/funds/models/submissions.py, opentech/apply/review/models.py
Link #1081 
Currently, a query is fired for each row in the submissions list table when [review author](https://github.com/OpenTechFund/opentech.fund/blob/2c8c3de93b4b9581a6aaaf99867d8cb0f9ad5f2b/opentech/apply/funds/templates/funds/tables/table.html#L43) and review [opinion author](https://github.com/OpenTechFund/opentech.fund/blob/2c8c3de93b4b9581a6aaaf99867d8cb0f9ad5f2b/opentech/apply/funds/templates/funds/tables/table.html#L52) is accessed in the template. Uses [Prefetch](https://docs.djangoproject.com/en/2.1/ref/models/querysets/#prefetch-objects) objects.
Also, are we using Opinion on the Review feature in the apply site? The code is present but not sure it is being used. If not we can update the modified code.
=> Improve perf by not firing db query when review author and review opinion author is accessed

opentech/apply/activity/messaging.py, opentech/apply/review/blocks.py, opentech/apply/review/models.py, opentech/apply/review/templates/review/review_detail.html, opentech/apply/review/views.py
=> Set sensible defaults for reviewer score fields.

opentech/static_src/src/app/src/containers/ReviewInformation.js
This was occurring because an `order` hadn't been set in the backend under Apply > Reviewer Roles > Secondary so the order value was `null`. Anyone with this value is now moved after those who have a value. Suggest we also make this field mandatory in the backend.
=> put people who don't have an order set after those who do

opentech/apply/funds/edit_handlers.py, opentech/apply/funds/models/applications.py
Closes #1069 
Currently, we display default value for a read-only field like workflow while creating a round page. The workflow default value is [single](https://github.com/OpenTechFund/opentech.fund/blob/322c41732872b9dc1e208273ff970fdcdb8066de/opentech/apply/funds/models/utils.py#L43) therefore [request](https://github.com/OpenTechFund/opentech.fund/blob/322c41732872b9dc1e208273ff970fdcdb8066de/opentech/apply/funds/workflow.py#L824) is displayed in the workflow field which creates confusion. It seems better to display nothing for workflow name like forms, review forms when a new round is being created. After a round is created, values are displayed which are copied from the parent Fund page.
=> Do not display workflow when a round is created to avoid confusion of default value

opentech/apply/funds/models/mixins.py, opentech/apply/funds/permissions.py, opentech/apply/funds/urls.py, opentech/apply/funds/views.py, opentech/apply/stream_forms/files.py, opentech/storage_backends.py
Closes #1168
Closes #637  
Closes #1108
The new URL for submission media can be accessed by users who have access to the submission detail view. The shareable URL will redirect to the actual file URL.
=> Submission private media shareable URL with permissions checks

opentech/apply/funds/models/submissions.py, opentech/apply/funds/templates/funds/includes/review_sidebar.html, opentech/apply/funds/templates/funds/includes/review_sidebar_item.html, opentech/apply/funds/templates/funds/tables/table.html, opentech/apply/funds/tests/test_models.py, opentech/apply/review/templates/review/review_list.html, opentech/apply/review/views.py, opentech/static_src/src/sass/apply/components/_list.scss, opentech/static_src/src/sass/apply/components/_reviews-list.scss
Current base is #985 - to be updated post merge
Tweaks the styling of the reviewers block in the table to give it more space and make the reviewer ordering logic consistent between all pages.
I've also snuck in #1205 because i was in the area.
=> GH-1191 Make reviewer ordering consistent and tweak styles on tables

opentech/apply/activity/messaging.py, opentech/apply/funds/workflow.py
Only send transition e-mail to users on forward status change.
Fixes #348
=> Add transitions to move status backwards when possible. 

opentech/apply/funds/differ.py, opentech/apply/funds/templates/funds/applicationrevision_list.html, opentech/apply/funds/views.py
Fixes #1299
Only allowing h4 (field labels), everything else is stripped. This allows the diff to concentrate on the text content.
=> Sanitising submission revision output before diff

opentech/apply/funds/tests/test_views.py
Got tired of seeing the notice on every test run.
=> Fix test notice complaining about naive datetime when timezone support is on

opentech/apply/funds/admin.py, opentech/apply/funds/tests/test_admin_views.py
This adds three columns to the Rounds admin page with links to the relevant related content:
* Sealed
* Applications
* Review Forms
It also converts the Fund column to a link as well.
Fixes #549
=> Link Rounds to Related Items

opentech/apply/determinations/tests/test_views.py, opentech/apply/determinations/views.py, opentech/apply/funds/models/submissions.py, opentech/apply/funds/tests/test_models.py, opentech/apply/funds/workflow.py
This creates a Project when an accepted Determination is applied to a submission.
I took the opportunity to refactor the `.form_valid()` method to add a fast failure condition to make it clearer that draft submissions are ignored.
Ref #1343
=> Create Project on Accepted Determination

opentech/apply/funds/templates/funds/applicationsubmission_detail.html, opentech/apply/projects/templates/application_projects/project_detail.html
This moves the Funding, Payment, & Invoice blocks from the Submission page to the Project page, leaving them hidden.
=> Move demo funding/payment/invoice blocks to the project page

opentech/apply/projects/templates/application_projects/project_admin_detail.html
Fixes incorrect copy on the assign-a-lead button as per [here](https://github.com/OpenTechFund/opentech.fund/issues/1328#issuecomment-518265160)
=> Rename Program Manager -> Lead

opentech/apply/funds/templates/funds/includes/delegated_form_base.html, opentech/apply/projects/templates/application_projects/project_admin_detail.html, opentech/apply/projects/views.py
This displays a warning to a user when they request Approval on a Project but haven't uploaded the recommended number of documents in each category.
Ref #1345
=> Confirm Project Approval with Missing Categories

opentech/apply/projects/templates/application_projects/project_detail.html, opentech/apply/projects/tests/test_views.py
Fixes a bug where the when there is no round on the submission (e.g. labs) the page fails to render. 
Also tests were not fully rendering the page, so rewrote to use the full request in order to get a working render. (could have done this on the class, but moved to be inline with other tests.
=> Fix sentry:OTF-WEBAPP-TEST-2G - projects of labs not rendering

opentech/apply/funds/templates/funds/applicationsubmission_admin_detail.html, opentech/apply/funds/templates/funds/applicationsubmission_detail.html, opentech/apply/projects/context_processors.py, opentech/settings/base.py
This adds a context processor to expose the `PROJECTS_ENABLED` setting to the template context, fixing a bug where we called the Wagtail provided `settings` for a value it didn't know about which always evaluated to falsey.
=> Fix Project Feature Flag

opentech/apply/dashboard/templates/dashboard/dashboard.html, opentech/apply/dashboard/views.py, opentech/apply/projects/tables.py
This adds a Projects table to the main admin Dashboard.
I've left the table unorderable since setting GET args on `AdminDashboardView` redirects off to another view currently.  Once [this](https://github.com/OpenTechFund/opentech.fund/issues/1340#issuecomment-522523638) is answered we can make a call on what to do.
=> Add Projects table to Staff dashboard

opentech/apply/determinations/tests/test_views.py, opentech/apply/determinations/views.py, opentech/settings/base.py, opentech/settings/dev.py, opentech/settings/test.py
This adds the `PROJECT_AUTO_CREATE` settings flag and uses it to enable/disable the automated creation of projects when a Submission is given an accepted determination.  The existing `PROJECTS_ENABLED` flag will still disable Project creation and general Project features regardless of `PROJECT_AUTO_CREATE`'s value.
=> Automatic Project Creation Feature Flag

requirements.txt
pydecimal complains about:
`TypeError: pydecimal() got an unexpected keyword argument 'min_value'`
for versions of faker < 1.0
=> Pin Faker version so that we dont come across the decimal API change

opentech/apply/funds/api_views.py, opentech/settings/base.py, requirements.txt
Closes #974 
API keys can be generated from `/django-admin/rest_framework_api_key/apikey/`
The generated API key will be shown only once while creating for better security. So, the admin user must note it down.
@frjo Initial PR for issue #974. OTF can test it and then we can make further enhancements. For testing, allowed one endpoint 
```
curl -X GET http://apply.localhost:8000/apply/api/submissions/ -H 'Authorization: Api-Key CHANGE-WITH-GENERATED-KEY'
```
=> API Key to access some endpoints

opentech/apply/funds/forms.py, opentech/apply/funds/models/submissions.py
Fixes #1572
We have various Update forms on submission detail page like a status update, partners, lead forms etc. Application submission model has a custom [save](https://github.com/OpenTechFund/opentech.fund/blob/9a740785a3f6375cc8ec4dd95dcce90de747033f/opentech/apply/funds/models/submissions.py#L601) method. And a portion of the code [saves](https://github.com/OpenTechFund/opentech.fund/blob/9a740785a3f6375cc8ec4dd95dcce90de747033f/opentech/apply/funds/models/submissions.py#L595) a new version of a file every time save method is invoked. It results in long filenames as file overwrite setting is False. The update forms on detail page do not need to run the custom code in the save method. Therefore adding a flag to skip the custom operation for these forms. This old PR #558 also seems …
=> Fix: New file versions created on status update, adding partner forms

.circleci/config.yml, .travis.yml, opentech/settings/dev.py, opentech/settings/local.py.example, opentech/urls.py, requirements-dev.txt, requirements.txt, vagrant/provision.sh
This sets up development dependencies so we're not installing testing libraries into production environments and installs the Django Debug Toolbar in development, configuring it so it's always running but with its panels disabled.  I've disabled the panels to cope with the prohibitive performance penalty some of the panels bring, but they can be toggled on in the UI easily.
=> Add Debug Toolbar to Dev

opentech/apply/funds/files.py, opentech/apply/funds/models/mixins.py, opentech/apply/funds/models/submissions.py, opentech/apply/funds/tests/test_models.py
Not related to the issue fixed. But we may need a strategy to only [save](https://github.com/OpenTechFund/opentech.fund/blob/2ffd404d628ad4f255ac3892cef306980f6e4a4d/opentech/apply/funds/models/mixins.py#L75) files if the existing files changes. Currently, a new file version is created even if the file is not changed in an edit form. Long file names have problems like #1572.
Fixes https://github.com/OpenTechFund/issues.otf/issues/13
=> Fix the creation of files under the submission's revision path 

opentech/apply/activity/messaging.py, opentech/apply/determinations/tests/test_views.py, opentech/apply/determinations/views.py, opentech/settings/base.py
Fixes: #1705
1. AttributeError: 'NoneType' object has no attribute 'page'
```shell
File "opentech/apply/activity/messaging.py", line 778, in send_message
from_email = source.submission.page.specific.from_address
```
Methods in messaging code use `source` value. In the case of the batch, the `source` is None. Therefore, errors like the above occur. Included code to extract `source` value from `sources` in `process_send` method so other methods can use the `source` value.
2. 
```shell
Exception Type: TypeError at /apply/submissions/batch-determine/
Exception Value: Direct assignment to the reverse side of a related set is prohibited. Use submission.set() instead.
```
Recently Activity model has updated and replaced `submission` field with a generic `source` field. Updated the code which was …
=> Fixes for Batch Determination creation

Makefile
- Add missing PHONY definition for `help`
- Add `lint` command to run both isort and flake8
- Add `style` command to run flake8
- Rename `fix` to `sort-fix` to fix the isort errors
- Remove exit code from `sort` as it hid errors and emits error codes anyway
=> Centralise linting commands in the makefile

hypha/apply/utils/pdfs.py, hypha/settings/test.py
- Only load truetype fonts when make_pdf is first called - affect first test run
- Use the basic md5 hash to avoid expensive has calcs with better hasher
- ~40% test speed up when there are users involved
=> General test performance tweaks

.circleci/config.yml, hypha/settings/test.py
This avoids the need to collect static files as part of the testing process
locally and in CI.
However - recommend updating CI to run collect static with the production
settings to ensure that all static files are present
Based on [recommendation in docs](https://docs.djangoproject.com/en/3.0/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.ManifestStaticFilesStorage)
> Due to the requirement of running collectstatic, this storage typically shouldn’t be used when running tests as collectstatic isn’t run as part of the normal test setup. During testing, ensure that the STATICFILES_STORAGE setting is set to something else like 'django.contrib.staticfiles.storage.StaticFilesStorage' (the default).
=> Convert the test staticfile storage to not be manifest

README.md
The current links do not work and that leads to 404 pages. This fix leads to correct pages and it will be beneficial for a newcomer to save time finding the deploy docs.
=> fix wiki links on readme file

hypha/apply/funds/forms.py
The PR https://github.com/OpenTechFund/hypha/pull/1768 was not a good solution and this PR reverts it.
It allowed staff to delete primary/secondary reviewers via the batch function. If the reviewer had already submitted a review it was deleted along with the reviewer. This is bad.
=> Revert: Allow staff reviewers to be deleted.

hypha/apply/dashboard/static/js/django_select2-checkboxes.js, hypha/apply/dashboard/static/js/select2.multi-checkboxes.js, hypha/static_src/src/sass/apply/components/_select2.scss, hypha/static_src/src/sass/public/components/_select2.scss, requirements.txt
fix #1792
Upgraded `django_select2` from `7.1.1` to `7.2.2` thus `select2js` upgraded from `3.5.x` to `4.x`.
Select2 4.0 introduced [AMD-based build](https://addyosmani.com/writing-modular-js/) so I have generated `select2.multi-checkboxes.js` from `amd` branch of [wasikuss/select2-multi-checkboxes](https://github.com/wasikuss/select2-multi-checkboxes/tree/amd).
`Select2 4.x` doesn't have `.wrap` class around dropdown text so I needed to change CSS in  hypha/static_src/src/sass/apply/components/_select2.scss.  
@frjo I wasn't sure if I need to change CSS for https://github.com/OpenTechFund/hypha/blob/master/hypha/static_src/src/sass/public/components/_select2.scss as I have gone through the code and I haven't found where it is used.
=> Upgrade Django Select 2

hypha/apply/determinations/views.py
I felt that was a mistake and made a small change.
Changed from
```python
raise ValueError('Submissions expect different forms - please contact and admin')
```
to 
```python
raise ValueError('Submissions expect different forms - please contact admin')
```
=> Fix sentence for determination forms for stages

hypha/apply/dashboard/templates/dashboard/dashboard.html
Fix #1880 
It was a simple spelling mistake, `awating_reviews` should have been `awaiting_reviews`.
=> Fix count of waiting review on Dashboard

hypha/settings/base.py
Fixes #1082 
Disable users password setting/change from Wagtail admin. As we have our own system to reset the password in the apply site. For new users created from Wagtail admin
>user will have no usable password; in order to log in, they will have to reset their password (if WAGTAIL_PASSWORD_RESET_ENABLED is True) or use an alternative authentication system such as LDAP (if one is set up). - [docs](https://docs.wagtail.io/en/v2.8.1/reference/settings.html#password-management)
=> Disable user password management from Wagtail admin

hypha/apply/users/admin_views.py, hypha/apply/users/templates/wagtailusers/users/list.html
Fixes #550 
Allow admin users to order users listing by status. We can not add order by roles as it gives
duplicate results due to
>Here, there could potentially be multiple ordering data for each Event; each Event with multiple children will be returned multiple times into the new QuerySet that order_by() creates. In other words, using order_by() on the QuerySet could return more items than you were working on to begin with - which is probably neither expected nor useful.
>Thus, take care when using multi-valued field to order the results. If you can be sure that there will only be one ordering piece of data for each of the items you’re ordering, this approach should not present problems. If not, make sure the results are what you expect. - …
=> Sort by active/inactive status in admin users listing

hypha/apply/funds/templates/funds/includes/table_filter_and_search.html, hypha/static_src/src/javascript/apply/batch-actions.js
Fixes #1882 
First bug:
> <img width="812" alt="Screenshot 2020-03-24 at 11 01 27" src="https://user-images.githubusercontent.com/7290588/77418508-e4ea5e00-6dbe-11ea-9a4a-6342c29f5f44.png">
> 
> I've tried to update a submission status for a single submission using the batch status changer but I get a message telling me it's not possible to change the status for this combination of submissions. 
**I don't see any problem in changing the status of single submission as bug mentioned in the issue.** 
The second bug: 
> Additionally when a status can be changed the message still displays. 
> 
> <img width="569" alt="Screenshot 2020-03-24 at 11 03 31" src="https://user-images.githubusercontent.com/7290588/77418706-2ed34400-6dbf-11ea-9f68-b7b6e4d2ea65.png">
> 
**This is fixed and now tooltip is …
=> don't show tooltip when status can be changed

hypha/apply/funds/models/submissions.py
This PR just remove the following line in ApplicationSubmission Modal.
`field_template = 'funds/includes/submission_field.html'`
Also, need to mention that there no such file, in this path `funds/includes/submission_field.html`
=> remove unused field_template on ApplicationSubmission Modal

hypha/apply/funds/admin.py
Fixes #1910 
Allow staff to delete application form that are not associated with round or lab.
=> Allow staff to delete appliation form

hypha/apply/projects/forms.py, hypha/apply/projects/tests/test_forms.py
Projects should not need to submit receipts as part of payment requests.
=> Make receipts an optional field on payment requrests

hypha/apply/activity/templates/messages/email/sent_to_compliance.html
Missing requirement on #1334 
Compliance should receive the links to the simplified views within the email
=> Send compliance the link to the simplified views

hypha/static_src/src/app/src/containers/DisplayPanel/index.js, hypha/static_src/src/app/src/containers/NoteListing.js
Fixes #1528 
I made some edits to the React app/detailed view of submission notes, so that when a user is editing a comment/note, the rich text editing form appears inline instead of having the users scroll down to the initial comment submit box.
=> Moving the edit comment UI to inline in detailed view

hypha/apply/determinations/templates/determinations/includes/determination_button.html, hypha/apply/funds/models/submissions.py, hypha/apply/funds/templates/funds/includes/actions.html, hypha/apply/funds/tests/test_views.py
This PR makes the 'Add determination' action prominent when an application is in the 'ready-for-determination' phase. When a user hasn't created a determination, 'Add determination' is displayed as a primary action. When a user has created a draft determination, 'Complete draft determination' is displayed.
=> Improve display of 'Add determination' action

hypha/apply/funds/templates/funds/includes/actions.html, hypha/apply/funds/templates/funds/includes/screening_status_block.html, hypha/apply/funds/tests/test_views.py, hypha/static_src/src/sass/apply/components/_link.scss
This PR makes the 'Screen application' action prominent when an application hasn't been screened. The 'Screen application' primary action is only displayed when an application's screening status hasn't been set. A 'Change' link has been added to the 'Screening Status' sidebar block to enable screening status to be changed after it has been set.
=> Improve display of screen application primary action

hypha/apply/funds/models/submissions.py, hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html, hypha/apply/funds/templates/funds/applicationsubmission_detail.html, hypha/apply/funds/templates/funds/includes/admin_primary_actions.html, hypha/apply/funds/templates/funds/includes/generic_primary_actions.html, hypha/apply/funds/templatetags/primaryactions_tags.py, hypha/apply/funds/tests/factories/models.py, hypha/apply/funds/tests/test_views.py, hypha/apply/review/templates/review/includes/review_button.html
This PR makes the 'Review' action prominent when an application in in internal or external review phases. When a user hasn't created a review, 'Create review' is displayed as a primary action. When a user has created a draft review, 'Complete draft review' is displayed. When a user has completed a review, the button is not displayed.
=> Improve display of Add Review action

requirements.txt
Security release https://docs.wagtail.io/en/stable/releases/2.8.2.html
=> Upgrade Wagtail for CVE-2020-11037

hypha/apply/funds/models/submissions.py, hypha/apply/funds/templates/funds/includes/admin_primary_actions.html, hypha/apply/funds/tests/test_views.py
This PR makes the 'Assign Reviewers' action prominent when an application is in review stage. When in internal review, the action is displayed until reviewers are assigned to all roles. When in external review, the action is always displayed.
=> Improve display of Assign Reviewers action

hypha/apply/review/views.py
`UserPassesTestMixin` used without `login_required` method decorator, raise 403 Permission Denied without giving user option to login first. It seems better to give the login option before checking permissions.
=> Give user login option before raising 403

hypha/apply/funds/models/submissions.py, hypha/apply/funds/templates/funds/includes/admin_primary_actions.html, hypha/apply/funds/templates/funds/includes/generic_primary_actions.html, hypha/apply/funds/templatetags/primaryactions_tags.py, hypha/apply/funds/tests/test_views.py
This PR makes the 'View determination' action prominent when an application has been determined (accepted or rejected). The button is visible to any user that has access to the submission.
=> Improve display of 'View determination' action

hypha/apply/categories/blocks.py, hypha/apply/categories/models.py, hypha/apply/determinations/models.py, hypha/apply/determinations/views.py, hypha/apply/funds/admin_helpers.py, hypha/apply/funds/admin_views.py, hypha/apply/funds/blocks.py, hypha/apply/funds/forms.py, hypha/apply/funds/models/__init__.py, hypha/apply/funds/models/applications.py, hypha/apply/funds/tables.py, hypha/apply/funds/views.py, hypha/apply/projects/forms.py, hypha/apply/projects/models.py, hypha/apply/projects/views/project.py, hypha/apply/review/blocks.py, hypha/apply/review/models.py, hypha/apply/stream_forms/blocks.py, hypha/apply/users/admin_views.py, hypha/apply/utils/blocks.py, hypha/apply/utils/views.py, hypha/public/forms/models.py, hypha/public/mailchimp/views.py
I noticed that `ugettext_lazy` is deprecated in Django 3 and only needed if the code support Python 2 from what I understand. Use `gettext_lazy` instead.
I also replaced all calls to `ugettext` and `gettext` with `gettext_lazy`.
=> Always use gettext_lazy.

hypha/apply/funds/templates/funds/submissions_result.html, hypha/apply/funds/views.py
Fixes #1999
We also need to do a one off cleanup of existing values in the db.
```
from hypha.apply.funds.models import ApplicationSubmission
submissions = ApplicationSubmission.objects.all().order_by('pk')
for s in submissions:
try:
value = s.data('value')
except KeyError:
pass
else:
value = str(value)
value = value.replace('USD', '')
value = value.replace('$', '')
value = value.replace('-', '')
value = value.replace(',', '')
try:
value_as_float = float(value)
except (TypeError, ValueError):
value = '0'
finally:
if s.data('value') and s.data('value') != value:
s.form_data['value'] = value
s.save(skip_custom=True)
```
=> Use db functions to calculate submission results. Performs significantly better.

hypha/apply/determinations/views.py, hypha/apply/middleware.py, hypha/public/home/templates/home/home_page.html, hypha/public/navigation/templatetags/navigation_tags.py, hypha/public/search/views.py, hypha/settings/base.py, hypha/templates/base-apply.html, hypha/templates/base.html, hypha/templates/includes/share.html, requirements.txt
Fixes https://github.com/OpenTechFund/hypha/issues/2011
In order to upgrade to Wagtail 2.9:
- We need to use `Site.find_for_request(request)` in place of `request.site` in Python files and tag `{% wagtail_site %}` in templates.
- And then remove `wagtail.core.middleware.SiteMiddleware` from the settings.
=> Upgrade to Wagtail 2.9

hypha/apply/funds/models/applications.py, hypha/apply/funds/models/submissions.py, hypha/apply/funds/models/utils.py, hypha/apply/funds/templates/funds/application_base.html, hypha/apply/funds/templates/funds/application_base_landing.html, hypha/apply/funds/tests/test_models.py, hypha/apply/funds/tests/test_views.py, hypha/apply/funds/views.py, hypha/apply/funds/workflow.py, hypha/apply/review/views.py, hypha/static_src/src/javascript/apply/submission-form-copy.js
Fixes #309 
Added Save Draft button on all fund pages.
When the applicant clicks on the Save Draft button, submission is considered as a `draft`. 
Following things are taken into consideration while building this feature. 
- The applicant can see and edit draft submission made in the dashboard.
- The applicant can edit and submit a submission that becomes `in_discussion` aka INITIAL_STATUS
- Staff cannot see draft submission made by the applicant also can't see in the submission list.
=> Allow Applicants to save application as a draft

vagrant/provision.sh
This is needed for example to be able to import a database dump created from postgres 12.
Also, not needed for postgres 12, but adding `PGDATABASE` to bashrc makes it possible to run `psql` without any arguments. This has to be added manually to existing vagrant boxes.
=> Upgrade to postgres 12 in vagrant

hypha/apply/dashboard/templates/dashboard/dashboard.html
Fixes https://github.com/OpenTechFund/hypha/issues/1884
Considering https://github.com/OpenTechFund/hypha/issues/1884 as reference, I think view label should also be disabled for the other cards when there is no data to view.
=> Disable view label from summary card when there is no data to view

hypha/apply/stream_forms/blocks.py, requirements.txt
Escape help text in stream forms like Wagtail's contrib form builder [update](https://github.com/wagtail/wagtail/blob/b98d724def7fc4d9310ecff2501f41b677d155bd/wagtail/contrib/forms/forms.py#L122) in security release.
https://docs.wagtail.io/en/v2.9.3/releases/2.9.3.html
=> Wagtail security release and escape help text in stream forms

hypha/apply/api/urls.py, hypha/apply/api/v1/views.py, hypha/settings/base.py, requirements.txt
This pr integrates with https://github.com/axnsan12/drf-yasg which will provide a nice UI to interact with all the APIs that we have.
Most of the information which one needs to interact with the APIs are automatically generated by `drf-yasg` and additional information can also be added inform of a doc string to the views.
This UI is currently available at `/api/doc/` endpoint.
=> Integrate drf-yasg for doc ui and document existing apis

hypha/apply/activity/templates/activity/include/listing_base.html, hypha/apply/api/v1/filters.py, hypha/apply/api/v1/mixin.py, hypha/apply/api/v1/serializers.py, hypha/apply/api/v1/tests/test_views.py, hypha/apply/api/v1/urls.py, hypha/apply/api/v1/views.py, requirements.txt
This pr makes following changes:
- Instead of creating separate API views for each methods we can use a single [viewsets](https://www.django-rest-framework.org/api-guide/viewsets/) class and then instead of hardcoding url patterns in urls.py, we can use [routers](https://www.django-rest-framework.org/api-guide/routers/) to make use of automatically generated url patterns.
- By using [drf-nested-routers](https://github.com/alanjds/drf-nested-routers) we can define `submission_router` and then register it's child url-views under that router. This makes easy for us to define any number of nested urls for a submission without hardcoding the patterns in urls.py. 
- moves filters from views.py to a separate file named `filters.py`.
=> Improve current apis to make use of drf viewset and routers

hypha/apply/funds/tables.py
=> Enable null_label in screening_status filter dropdown to be able to filter applications without screening status
