OpenTechFund/hypha

opentech/apply/workflow.py
opentech/settings/base.py

Updates to the workflow as per your comments @zerolab

Add doc strings into the workflow and fix the bug in single stage

---

fabfile.py

Correctly capture the value of the command so that we compare something.

Return the value from the local call

---

opentech/apply/categories/blocks.py
opentech/apply/categories/models.py
opentech/apply/categories/tests.py
opentech/apply/categories/tests/factories.py
opentech/apply/categories/tests/test_blocks.py

Add tests to cover the category block implementation.

Tests for category block

---

fabfile.py

Adds `build_branch` parameter for `_deploy_static`
and adds command to deploy to preproduction
Note: no pulling media/data yet

fabfile tweaks

---

fabfile.py

Ideally, I'd like to move to a `fab env:ENV deploy|pull_data|pull_media` model
This has the first step towards that

Add dev instance and tweak fabfile

---

fabfile.py

Update the database names and dump locations

---

opentech/public/utils/wagtail_hooks.py
opentech/settings/base.py

Remove forms from the user

---

opentech/apply/home/templates/apply_home/includes/apply_listing.html

@chris-lawton for reference as this might affect your styling work in #104

Update the listing to only show funds/labs with open rounds

---

opentech/public/navigation/templatetags/navigation_tags.py
opentech/public/utils/context_processors.py
opentech/templates/includes/apply_button.html

This add the navigation settings to the top of the apply site for public pages

Share the navigation settings across the public part of apply

---

opentech/apply/funds/models.py
opentech/apply/funds/tests/factories/blocks.py
opentech/apply/funds/tests/factories/models.py
opentech/apply/funds/tests/test_models.py
opentech/apply/stream_forms/blocks.py

Image field wasnt being processed correctly.

Add a base class to uploadable media to reduce errors

---

opentech/apply/users/management/commands/migrate_users.py

was faster than anonymising the JSON

Add anonymisation option to user migration

---

opentech/apply/dashboard/templates/dashboard/applicant_dashboard.html
opentech/apply/funds/tables.py

@chris-lawton 
This should allow the child table to correctly display the status on the submissions table

Correctly inherit the meta for the child tables

---

opentech/apply/funds/management/commands/seed_rapid_response.py

was missing from the migration

Fix RR round form assignment

---

opentech/apply/funds/tables.py

Lead is now stored on the submission rather than the round.

Correctly look at the lead attribute on the submission

---

opentech/apply/funds/templates/funds/includes/review_table.html

Prevent many trailing numbers after the decimal point.
rounds to int if `x.0` else 1 decimal place.

Ensure that the score is formatted in a reasonable way

---

opentech/static_src/src/sass/apply/components/_select2.scss

fix styling of select2 dropdowns in modals

add z-index to select2 dropdowns to appear higher than than modal

---

opentech/apply/urls.py
opentech/apply/users/decorators.py
opentech/apply/users/templates/users/account.html
opentech/apply/users/urls.py
opentech/apply/users/views.py
opentech/settings/base.py
opentech/templates/base-apply.html
requirements.txt

This allows super admins to assume the role of another user, we may end up removing this when the site is live, but it will make testing the site during MVP much easier.

Allow superusers to log in as other users

---

opentech/apply/dashboard/templates/dashboard/applicant_dashboard.html
opentech/static_src/src/sass/apply/components/_wrapper.scss

Fixes edit button appearing strangely ~tablet and desktop breakpoints

split status bar wrapper into inner and outer to accommodate edit button

---

opentech/apply/dashboard/templates/dashboard/dashboard.html
opentech/apply/dashboard/tests/test_views.py
opentech/apply/dashboard/views.py
opentech/apply/funds/models.py
opentech/apply/funds/workflow.py

Adds a table for submissions in determination phases for the lead (or admin)

Add applications awaiting determination for leads/superusers

---

opentech/apply/funds/workflow.py

Hi Dan, can you look at writing a few tests for this or making sure that this is fine in the future.

Enable external reviews for proposal

---

opentech/public/utils/context_processors.py
opentech/templates/base-apply.html
opentech/templates/base.html

remove google tag manager

---

opentech/apply/funds/templates/funds/includes/review_table.html
opentech/static_src/src/sass/apply/components/_all-submissions.scss
opentech/static_src/src/sass/apply/components/_reviews-sidebar.scss

Addressing feedback here - https://projects.torchbox.com/projects/otf-website-and-proposal-system/tickets/296

296 fe tweaks

---

opentech/static_src/src/sass/apply/components/_form.scss
opentech/static_src/src/sass/apply/components/_submission-meta.scss

Addressing feedback [here](https://projects.torchbox.com/projects/otf-website-and-proposal-system/tickets/297#update-52693180)

297 fe pre launch fixes

---

opentech/apply/activity/templates/messages/email/determination.html
opentech/apply/dashboard/templates/dashboard/dashboard.html
opentech/apply/determinations/templates/determinations/determination_detail.html
opentech/public/utils/templates/utils/includes/login_button.html
opentech/templates/base-apply.html
opentech/templates/base.html

Also fixes #445 in the process

make sure we have the correct page titles

---

opentech/static_src/src/sass/apply/abstracts/_variables.scss
opentech/static_src/src/sass/apply/components/_all-submissions.scss
opentech/static_src/src/sass/apply/components/_button.scss
opentech/static_src/src/sass/apply/components/_feed.scss
opentech/static_src/src/sass/apply/components/_grid.scss
opentech/static_src/src/sass/apply/components/_icon.scss
opentech/static_src/src/sass/apply/components/_messages.scss
opentech/static_src/src/sass/apply/components/_tabs.scss
opentech/static_src/src/sass/public/abstracts/_functions.scss
opentech/static_src/src/sass/public/abstracts/_mixins.scss
opentech/static_src/src/sass/public/abstracts/_variables.scss
opentech/static_src/src/sass/public/components/_icon.scss
opentech/static_src/src/sass/public/components/_listing.scss
opentech/static_src/src/sass/public/components/_messages.scss
opentech/static_src/src/sass/public/components/_nav.scss
opentech/static_src/src/sass/public/components/_pagination.scss
opentech/static_src/src/sass/public/layout/_footer.scss
opentech/static_src/src/sass/public/layout/_header.scss
opentech/static_src/src/sass/public/main.scss
opentech/templates/includes/pagination.html

- changes blue hexes
- lint styles
- adds pagination styles for public site

303 fe tweaks

---

opentech/settings/base.py
requirements.txt

we already set the referrer policy but we failed to include the middleware and package.
https://github.com/OpenTechFund/opentech.fund/blob/97eb19946285b1240164c60fd26211c894f2620b/opentech/settings/base.py#L575-L576

Add referrer package and middleware

---

opentech/apply/funds/models/mixins.py

1070 queries down to 33
Fixes #562

Fix slow Submission list view

---

Procfile

https://devcenter.heroku.com/articles/release-phase#defining-a-release-command
https://stackoverflow.com/questions/36410107/running-manage-py-migrate-during-heroku-deployment

Add a release phase to Heroku Procfile to autorun migration on deploy.

---

opentech/apply/categories/blocks.py
opentech/apply/categories/tests/test_blocks.py
opentech/apply/funds/models/submissions.py
opentech/apply/funds/tests/test_views.py
opentech/apply/funds/workflow.py

fixes #628 
The status of the application has not been updated when the transition method is called. So we need to find out where we are transitioning to and the use that to get the new `form_fields`.

Make sure we get the new form_fields for the transition

---

opentech/apply/activity/templates/messages/email/determination.html

Add all feedback fields to the determination e-mail.

---

opentech/apply/funds/views.py

temporary fix for #647 - prevent users from saving

Remove the save draft from the options (temporarily)

---

opentech/apply/funds/views.py

This reverts commit 63bb615962e02ce3375ba993d064583496d72c8d.

Revert "Remove the save draft from the options (temporarily)"

---

opentech/templates/includes/relatedcontent_card.html

Fix for related pages with no deadline always show as Closed.

---

opentech/apply/funds/workflow.py

Use Dismiss instead of Reject for display of rejeced state.

---

opentech/apply/funds/templates/funds/applicationsubmission_detail.html
opentech/apply/funds/views.py
opentech/static_src/src/sass/apply/components/_link.scss

Link the fund/lab on a submission detail viewto the public fund/lab page

---

opentech/static_src/src/sass/print.scss
opentech/static_src/src/sass/public/abstracts/_mixins.scss
opentech/templates/base-apply.html
opentech/templates/base.html

CSS for print.

---

opentech/apply/funds/templates/funds/applicationsubmission_admin_detail.html
opentech/static_src/src/javascript/apply/toggle-sidebar.js

Add a javascript link to toggle the sidebar on submission pages for admins

---

opentech/apply/funds/templates/funds/includes/rendered_answers.html

Fixes #649 
Will make the link inline in another pr.

Add edit account link on submissions for otf staff.

---

opentech/apply/funds/models/submissions.py
opentech/apply/funds/tables.py

Add the full name field to submission search and make it less slow.

---

opentech/apply/activity/tests/test_messaging.py
opentech/apply/funds/models/applications.py
opentech/apply/funds/templates/funds/submissions_by_round.html
opentech/apply/funds/tests/factories/models.py
opentech/apply/funds/tests/test_views.py
opentech/apply/funds/urls.py
opentech/apply/funds/views.py

#773 base submission by round page

---

opentech/static_src/src/app/src/components/SubmissionDisplay/answers.js

Fixes the issue with answers not being able to render in some cases
@tm-kn @chris-lawton  FYI

Add in text answer type and fallback to Basic Answer if nothing defined

---

opentech/apply/funds/templates/funds/includes/round-block-listing.html
opentech/static_src/src/sass/apply/components/_round-block.scss

- makes the round title a link
- show the round list item borders on hover

make round title a link and show borders on item hover

---

opentech/apply/funds/templates/funds/includes/review_table_row.html
opentech/apply/review/templates/review/review_detail.html
opentech/static_src/src/sass/apply/abstracts/_functions.scss
opentech/static_src/src/sass/apply/components/_reviews-sidebar.scss

Display updated date for reviews.

---

opentech/static_src/src/app/src/containers/DisplayPanel/index.js

Fixes: #923
This works but I assume there is a better way to build the link?

Add a link that opens the submission in a new tab on the react round view

---

opentech/static_src/src/app/src/api/notes.js
opentech/static_src/src/app/src/api/rounds.js
opentech/static_src/src/app/src/api/submissions.js
opentech/static_src/src/app/src/api/utils.js
opentech/static_src/src/app/src/redux/actions/notes.js
opentech/static_src/src/app/src/redux/actions/submissions.js
opentech/static_src/src/app/src/redux/middleware/api.js
opentech/static_src/src/app/src/redux/reducers/submissions.js
opentech/static_src/src/app/src/redux/store.js
opentech/static_src/src/app/webpack.base.config.js
package-lock.json
package.json

@tm-kn How do you feel about these changes?

Refactor how the api works to reduce boilerplate

---

opentech/static_src/src/app/src/api/index.js
opentech/static_src/src/app/src/api/notes.js
opentech/static_src/src/app/src/api/rounds.js
opentech/static_src/src/app/src/api/submissions.js
opentech/static_src/src/app/src/api/utils.js
opentech/static_src/src/app/src/components/GroupedListing/index.js
opentech/static_src/src/app/src/components/ListingDropdown/index.js
opentech/static_src/src/app/src/containers/ByStatusListing.js
opentech/static_src/src/app/src/redux/actions/notes.js
opentech/static_src/src/app/src/redux/actions/submissions.js
opentech/static_src/src/app/src/redux/middleware/api.js
opentech/static_src/src/app/src/redux/reducers/rounds.js
opentech/static_src/src/app/src/redux/reducers/submissions.js
opentech/static_src/src/app/src/redux/selectors/submissions.js
opentech/static_src/src/app/src/redux/store.js
opentech/static_src/src/app/webpack.base.config.js
package-lock.json
package.json

@tm-kn main reviewer. Would appreciate going over the fetching logic especially about loading and error states.
@chris-lawton can you confirm that you are happy with any of the drop down changes, functionally nothing should have changes

rounds fetching and ordering

---

opentech/public/forms/templates/public_forms/form_page.html
opentech/public/forms/templates/public_forms/form_page_landing.html

Add markup and classes to styles are applied to the wagtail forms.

---

opentech/static_src/src/app/src/components/GroupedListing/index.js

In mobile view we didnt have enough component updates to actually show anything. This now has the right amount.

Make sure we update when internal state changes

---

opentech/apply/funds/forms.py
opentech/apply/funds/tests/test_views.py

Allow staff to set screening status on all submissions, active and inactive

---

opentech/static_src/src/sass/public/components/_messages.scss

- adds updated message styling to the public site

adds updated message style to public site

---

opentech/apply/stream_forms/blocks.py

closes #1001 
@frjo FYI - might be worth getting in tomorrow morning as a hotfix.

GH-1001: Don't attempt to serialize files if they have no info

---

opentech/apply/funds/templates/funds/includes/status-block.html
opentech/apply/funds/templates/funds/submissions_overview.html
opentech/static_src/src/sass/apply/components/_status-block.scss
opentech/static_src/src/sass/apply/main.scss

- Adds mock data and styles for the status block

adds mock status block

---

opentech/apply/funds/templates/funds/includes/status-block.html
opentech/apply/funds/views.py
opentech/apply/funds/workflow.py
opentech/static_src/src/sass/apply/components/_status-block.scss

@chris-lawton as discussed, small issue with heights of text. Do you want to tweak the styles here?
@emullaney FYI the boxy style above is correct and was approved in #867 it wont match what is shown in #866

GH-866: wire up the status block to the data

---

opentech/apply/funds/tables.py

Show all submission leads, not only round leads, in leads filter.

---

opentech/apply/funds/workflow.py

Allow staff to edit accepted submissions.

---

opentech/apply/activity/messaging.py

Always send to default plus custom slack channel.

---

opentech/apply/funds/views.py
opentech/apply/funds/workflow.py

Allow applicants to edit approved submissions.

---

opentech/apply/activity/messaging.py

Remove staff Slack notifications and staff e-mails for READY_FOR_REVIEW.

---

opentech/apply/activity/messaging.py
opentech/apply/activity/tests/test_messaging.py

Refactor the extra slack channels methods to behave in a more consistent manner. Always returning an iterate and simplified logic.

GH-1061: Update the slack message handling to be more graceful

---

opentech/apply/dashboard/templates/dashboard/dashboard.html
opentech/apply/dashboard/templates/dashboard/includes/waiting-for-review.html
opentech/apply/dashboard/templates/dashboard/reviewer_dashboard.html
opentech/apply/dashboard/views.py
opentech/apply/funds/models/submissions.py
opentech/apply/funds/tables.py
opentech/apply/funds/workflow.py

Filter the views with submission to review and have been reviewed to active statuses

---

opentech/apply/users/admin_views.py
opentech/apply/users/models.py
opentech/apply/users/wagtail_hooks.py

Allow both e-mail and full name to be searched for users in wagtail admin.

---

opentech/apply/funds/templates/funds/applicationsubmission_admin_detail.html
opentech/apply/funds/templates/funds/includes/update_partner_form.html

Load missing javascript for Select2MultiCheckboxesWidget.

---

opentech/apply/funds/templates/funds/application_base.html
opentech/apply/templates/forms/includes/field.html
opentech/static_src/src/javascript/apply/file-uploads.js
opentech/static_src/src/sass/apply/components/_form.scss
opentech/static_src/src/sass/public/components/_form.scss

Add a javascript that displays the files that a user has uploaded.

---

opentech/apply/stream_forms/blocks.py
opentech/apply/stream_forms/fields.py
opentech/apply/stream_forms/testing/factories.py
opentech/apply/stream_forms/tests.py
opentech/settings/base.py

Closes #1099 
Frontend and Backend checks for files being uploaded. Only allow files with specific extensions.

Allow only specific files in Uploads

---

opentech/static_src/src/sass/apply/components/_reviews-list.scss

Allow four reviews to be displayed side by side without need for scrolling

---

opentech/apply/funds/templates/funds/tables/table.html

Add screening status in submission list view extended section.

---

opentech/public/funds/models.py
opentech/public/news/models.py
opentech/public/news/templates/news/news_index.html
opentech/public/people/models.py
opentech/public/people/templates/people/person_index_page.html
opentech/public/projects/models.py
opentech/public/standardpages/models.py
opentech/public/standardpages/templates/standardpages/index_page.html
opentech/public/utils/templates/utils/listing_index.html
opentech/public/utils/wagtail_hooks.py
opentech/static_src/src/sass/apply/wagtail_editor.scss

Add markdown filter to index pages introductions.

---

opentech/apply/funds/templates/funds/applicationsubmission_detail.html

Link the round and the lead in submission header for staff.

---

opentech/apply/funds/views.py

Allow reviewers and partners to access their own submissions as applicants

---

opentech/apply/funds/models/submissions.py
opentech/apply/funds/views.py
opentech/apply/funds/workflow.py
opentech/apply/utils/views.py

Allow community reviewers to review submissions in a community review state

---

opentech/apply/activity/messaging.py
opentech/apply/activity/tests/test_messaging.py

Notify Second Reviewer when First Review is finished.

---

opentech/public/home/models.py

Only show open funds and labs on public homepage.

---

opentech/apply/determinations/tests/test_views.py
opentech/apply/determinations/views.py

Appends the `next` query param to help redirect the user back on a successful determination.

GH-1130: Redirect back to origin on batch determine

---

opentech/apply/funds/templates/funds/applicationsubmission_admin_detail.html
opentech/apply/funds/templates/funds/applicationsubmission_detail.html
opentech/static_src/src/javascript/apply/toggle-related.js
opentech/static_src/src/sass/apply/components/_related-sidebar.scss
opentech/static_src/src/sass/apply/main.scss

Make it possible to toggle the related sidebar if to long.

---

opentech/templates/base.html

Reuse parent header image if page has none.

---

opentech/public/projects/models.py

Order project index pages by first_published_at desc.

---

opentech/apply/stream_forms/templates/stream_forms/includes/file_field.html

Open submission upload file link in a new tab.

---

opentech/apply/funds/urls.py
opentech/apply/funds/views.py
opentech/storage_backends.py

Discussed here https://github.com/OpenTechFund/opentech.fund/issues/1168#issuecomment-495614598

Serve private media instead of S3 redirect for a submission

---

opentech/apply/users/models.py
opentech/apply/users/templates/wagtailusers/users/list.html

Add roles to the user admin index page.

---

opentech/apply/users/models.py
opentech/apply/users/wagtail_hooks.py
opentech/apply/utils/notifications.py

Notify via Slack when new user is created or edited manually.

---

opentech/apply/funds/api_views.py

New filters for Submissions list endpoint and fix active filter

---

opentech/apply/funds/templates/funds/application_base.html

Change the Submit button for all applications to Submit for review.

---

package-lock.json

Node packages updates with the help of `npm audit fix` to fix security alerts.

Updating node packages.

---

opentech/apply/activity/messaging.py

Bugfix for notification to second reviewer.

---

opentech/apply/determinations/views.py

Fix to allow reviewers to access determinations.

---

opentech/apply/funds/templates/funds/applicationsubmission_admin_detail.html
opentech/apply/funds/templates/funds/includes/rendered_answers.html
opentech/static_src/src/javascript/apply/toggle-proposal-info.js
opentech/static_src/src/sass/apply/components/_grid.scss
opentech/static_src/src/sass/apply/components/_link.scss
opentech/static_src/src/sass/apply/components/_rich-text.scss

- Adds 'show more' block styles and example markup

add show more block

---

opentech/apply/determinations/views.py
opentech/apply/funds/models/submissions.py
opentech/apply/funds/templates/funds/includes/actions.html
opentech/apply/funds/templates/funds/includes/project_block.html
opentech/apply/projects/templates/application_projects/project_detail.html

Some general tidy of the Front End and make the logic cleaner by deferring to the Submission object.

Defer checking if accepted to the submission and tidy up FE

---

opentech/apply/funds/tests/test_models.py

This potentially fixes the intermittent submission test.  I was unable to stably recreate the error though so it's hard to tell.

Fix Intermittent Submission Test

---

.circleci/config.yml
.travis.yml
opentech/apply/funds/templates/funds/applicationsubmission_admin_detail.html
opentech/apply/funds/templates/funds/applicationsubmission_detail.html
opentech/apply/projects/models.py
opentech/apply/projects/tests/test_settings.py
opentech/apply/projects/urls.py
opentech/settings/base.py

This gates the Projects feature behind an environment variable controlled flag.
Ref #1346

Add Projects Feature Flag

---

opentech/apply/funds/models/mixins.py
opentech/apply/funds/templates/funds/applicationsubmission_simplified_detail.html
opentech/apply/funds/tests/test_views.py
opentech/apply/funds/urls.py
opentech/apply/funds/views.py

This adds the simplified Submission page.

Add Simplified Submission Page

---

opentech/apply/funds/forms.py
opentech/apply/funds/workflow.py

Sort the transitions by the order they are listed.

---

opentech/apply/utils/options.py
opentech/settings/base.py

Allow more table tags and add table button to editor.

---

opentech/apply/projects/templates/application_projects/includes/supporting_documents.html
opentech/static_src/src/sass/apply/components/_button.scss
opentech/static_src/src/sass/apply/components/_docs-block.scss

Corrects styling of supporting docs table after BE was implemented

adjust styling of remove upload button after the backend was added

---

opentech/apply/funds/templates/funds/includes/delegated_form_base.html
opentech/apply/projects/templates/application_projects/project_detail.html

This applies the field template include used for the Application Form so we get the same styling for file uploads and checkboxes.

Fix File and Checkbox Elements on Modal Forms

---

opentech/apply/projects/templates/application_projects/project_simplified_detail.html
opentech/apply/projects/tests/test_views.py
opentech/apply/projects/urls.py
opentech/apply/projects/views.py

This adds the Simplified Project page minus fields being added in #1364.

Simplified Project Page

---

opentech/apply/projects/files.py
opentech/apply/projects/forms.py
opentech/apply/projects/templates/application_projects/includes/supporting_documents.html
opentech/apply/projects/tests/test_files.py
opentech/apply/projects/tests/test_forms.py
opentech/apply/projects/urls.py
opentech/apply/projects/views.py
requirements.txt

This adds the "choose file" option to Supporting Documents to pick files from the related Submission.

Select Document from Submission

---

opentech/apply/projects/models.py
opentech/apply/projects/templates/application_projects/project_detail.html
opentech/apply/projects/tests/test_templatetags.py

This tweaks so Project page bits so we conform to the expectations of #1379.  I've also used it to capture some other little bugs I found along the way.

Project In Progress State

---

opentech/apply/dashboard/templates/dashboard/dashboard.html
opentech/apply/dashboard/tests/test_views.py
opentech/apply/dashboard/views.py
opentech/apply/projects/tables.py

This adds a Payment Requests summary table to the Staff dashboard.

Add Payment Requests Table to Staff Dashboard

---

opentech/apply/dashboard/templates/dashboard/applicant_dashboard.html
opentech/apply/dashboard/views.py

This adds Project and Payment Request summary tables to the Applicant dashboard.

Applicant Dashboard Project Summary

---

opentech/public/funds/templates/public_funds/lab_page.html
opentech/templates/includes/relatedcontent.html

Use default related header on labs.

---

opentech/apply/users/views.py

Fixes https://github.com/OpenTechFund/opentech.fund/issues/1468

Add next query to Google login link.

---

opentech/apply/activity/messaging.py
opentech/apply/activity/templates/messages/email/applicant_base.html
opentech/apply/activity/templates/messages/email/base.html
opentech/apply/activity/templates/messages/email/invited_to_proposal.html
opentech/apply/dashboard/templates/dashboard/partner_dashboard.html
opentech/apply/dashboard/templates/dashboard/reviewer_dashboard.html
opentech/apply/funds/permissions.py
opentech/apply/funds/templates/funds/application_base_landing.html
opentech/apply/funds/templates/funds/demo_workflow.html
opentech/apply/funds/templates/funds/email/confirmation.html
opentech/apply/funds/workflow.py
opentech/apply/users/templates/users/activation/email.txt
opentech/apply/users/templates/users/activation/invalid.html
opentech/apply/users/templates/users/login.html
opentech/apply/users/utils.py
opentech/public/utils/context_processors.py
opentech/public/utils/templates/utils/includes/login_button.html
opentech/settings/base.py

Use settings for organisation name etc. in templates.

---

opentech/apply/projects/filters.py
opentech/apply/projects/models.py
opentech/apply/projects/tables.py
opentech/apply/projects/templates/application_projects/includes/payment_requests.html
opentech/apply/projects/templates/application_projects/payment_request_list.html
opentech/apply/projects/templates/application_projects/paymentrequest_detail.html
opentech/apply/projects/tests/test_views.py
opentech/apply/projects/urls.py
opentech/apply/projects/views/payment.py
opentech/apply/projects/views/project.py

This adds the Payment Request List page.

Payment Request List View

---

opentech/static_src/src/app/src/api/notes.js
opentech/static_src/src/app/src/containers/AddNoteForm.js
opentech/static_src/src/app/src/containers/StatusActions.js
package-lock.json

Fixes https://github.com/OpenTechFund/opentech.fund/issues/1498
Fixes https://github.com/OpenTechFund/opentech.fund/issues/1503

Update visibility from internal -> team in react app and add executionActionError to prop-types

---

opentech/apply/funds/differ.py
opentech/apply/funds/templates/funds/includes/revision_diff_table.html
opentech/apply/funds/templates/funds/revisions_compare.html
opentech/apply/funds/views.py
opentech/static_src/src/sass/apply/components/_revisions.scss

Implement side by side submission revision diff

---

opentech/apply/users/wagtail_hooks.py

Include administrator setting on user update notification.

---

opentech/apply/funds/templates/funds/application_base.html
opentech/apply/utils/options.py
opentech/static_src/src/javascript/apply/tinymce-word-count.js
opentech/static_src/src/sass/apply/components/_rich-text.scss
opentech/static_src/src/sass/public/components/_rich-text.scss

Add word count to tinymce editor.

---

opentech/apply/determinations/forms.py

Fix determination forms save draft feature

---

opentech/apply/dashboard/templates/dashboard/dashboard.html
opentech/apply/dashboard/tests/test_views.py
opentech/apply/dashboard/views.py

This adds stats blocks to the Staff dashboard page.

Add Stats Blocks to Staff Dashboard

---

opentech/apply/dashboard/templates/dashboard/dashboard.html
opentech/apply/dashboard/tests/test_views.py
opentech/apply/dashboard/views.py
opentech/apply/projects/models.py
opentech/apply/projects/views/project.py

This adds the Projects to approve summary table to the Dasboard view.

Projects to Approve

---

opentech/apply/funds/workflow.py

Add revert from proposal_determination to post_proposal_review_discussion

---

opentech/settings/production.py

Fixes #1561
Alternativ to https://github.com/OpenTechFund/opentech.fund/pull/1564

Make the production settings work on more enviroments than Heroku.

---

opentech/apply/funds/templates/funds/application_base.html
opentech/public/forms/templates/public_forms/form_page.html

Move the javascript form warning to bottom to avoid flicker.

---

opentech/apply/review/management/commands/export_reviews_csv.py

Fixes https://github.com/OpenTechFund/issues.otf/issues/8

Added a export_reviews_csv command.

---

opentech/apply/activity/views.py

Reduce DB queries for Activity

---

opentech/static_src/src/sass/apply/components/_stat-block.scss

Make the top boxes on the dashbord take up less space.

---

opentech/apply/projects/templates/application_projects/includes/report_line.html

Branched from https://github.com/OpenTechFund/opentech.fund/pull/1656
- Adds report skip confirmation modal

add skip report confirmation modal

---

opentech/apply/funds/models/submissions.py

Minor improvement in DB queries while populating Tables. Link #1608

Reduce DB queries for Table data

---

opentech/settings/base.py

Set TIME_ZONE to UTC to avoid summertime.

---

opentech/static_src/src/javascript/apply/submission-text-cleanup.js
opentech/static_src/src/sass/apply/abstracts/_variables.scss
opentech/static_src/src/sass/apply/components/_feed.scss
opentech/static_src/src/sass/apply/components/_rich-text.scss

Make big tables and long links etc fit within the layout

---

opentech/apply/funds/admin.py
opentech/apply/funds/admin_helpers.py
opentech/apply/funds/admin_views.py

Admin: Create copy button in Application form

---

opentech/apply/funds/admin.py
opentech/apply/funds/admin_helpers.py

Add a open/closed filter to the round admin page in wagtail admin.

---

opentech/apply/funds/templates/funds/includes/review_sidebar_item.html

Fix template logic so reviewers can edit their reviews.

---

opentech/apply/projects/models.py

Handle empty address on application projects.

---

opentech/apply/funds/edit_handlers.py
opentech/apply/funds/models/submissions.py
opentech/apply/projects/admin.py
opentech/apply/projects/tests/test_views.py
opentech/apply/projects/views/project.py
opentech/apply/utils/admin.py
requirements.txt

Updates to Django 2.2.x LTS and Wagtail 2.7.

---

opentech/apply/activity/templates/messages/email/applicant_base.html
opentech/apply/activity/templates/messages/email/comment.html
opentech/apply/activity/templates/messages/email/determination.html

Remove sensitive information from determination and comments e-mails.

---

opentech/apply/projects/templates/application_projects/includes/supporting_documents.html
opentech/static_src/src/sass/apply/components/_docs-block.scss

Reduce size of the application project form.

---

opentech/apply/utils/options.py

Set relative_urls to false for TinyMCE.

---

opentech/apply/funds/forms.py

Allow staff reviewers to be deleted.

---

requirements.txt

Reverts OpenTechFund/hypha#1782

Revert "Bump django-select2 from 7.1.1 to 7.2.0"

---

hypha/apply/funds/blocks.py

Requested Funding value should be positive

---

hypha/templates/base.html

Only add root url to local social images not to S3 hosted ones

---

hypha/apply/utils/options.py

Activate browser_spellcheck in TinyMCE editor.

---

hypha/apply/activity/models.py
hypha/apply/api/v1/views.py

Fixes #1527
Hi there! Found and fixed some typos that were causing the error in #1527. The notes on the React app should be updating dynamically now, but I do want to flag that it it's not triggering the Slack notification flag at the top of the page, which is maybe a separate bug. 
P.S. Sorry for my branch name -- will follow your convention for my next PRs!

Fixed typos that was causing errors in react notes editor

---

hypha/apply/users/management/commands/accounts_cleanup.py

Add a account clenup command.

---

hypha/settings/base.py

Better options for default time and date formats.

---

hypha/apply/activity/templates/messages/email/applicant_base.html
hypha/apply/activity/templates/messages/email/invited_to_proposal.html

Small change to wording in the invite for proposal e-mail.

---

hypha/apply/funds/tables.py

Add meta term filter to submission tables.

---

hypha/static_src/src/javascript/apply/submission-form-copy.js

Add user input to the submission form copy javascript.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement-request.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
LICENSE

Fixes #1897
Fixes #1898
Add pull request template and CONTRIBUTING.md file. 
Minor fixe to LICENCE, make it clear that it is a BSD 3-Clause License.
Minor fixes to issue template files, adding empty lines after each header.

Add pull request template, CONTRIBUTING.md and minor fixes to LICENCE and issue template files

---

hypha/apply/review/templates/review/review_list.html
hypha/static_src/src/sass/apply/components/_reviews-list.scss
hypha/static_src/src/sass/apply/components/_wrapper.scss

Fixes #1038
Makes the table header with review author names stick to the top when scrolling the table, this make it possible to always see the author.

Make the header with review authors of the reviews list table sticky.

---

requirements.txt

Possible XSS attack via page revision comparison view https://github.com/wagtail/wagtail/security/advisories/GHSA-v2wc-pfq2-5cm6

Wagtail security release

---

hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
hypha/apply/dashboard/views.py

Fixes #1936 
Refactored Dashboard View.
- `ReviewerDashboardView` now only have 2-3 functions and made changes required in `reviewer_dashboard.html`.
- Created `MySubmissionContextMixin` class to be extended by `ReviewerDashboardView`, `PartnerDashboardView` and `CommunityDashboardView`.
- Got rid of `qs` word from the file.
- Use of `context.update()`

Refactor dashboard views

---

hypha/apply/dashboard/templates/dashboard/dashboard.html
hypha/apply/dashboard/templates/dashboard/includes/flagged.html
hypha/apply/dashboard/templates/dashboard/reviewer_dashboard.html
hypha/apply/dashboard/views.py
hypha/apply/flags/views.py
hypha/apply/funds/templates/funds/applicationsubmission_reviewer_detail.html
hypha/apply/funds/templates/funds/submissions_user_flagged.html
hypha/apply/funds/views.py

Make it so reviewers can flag submission.

---

hypha/static_src/src/javascript/apply/submission-form-copy.js

Fixes #1959
Adds help text, help links, word limit and checkbox options.

Add help text and links to application form copy

---

hypha/apply/utils/views.py
hypha/urls.py

Display a warning to admin user in case a page model like Fund, Round can not be deleted due to ProtectedError exception

---

hypha/apply/funds/templates/funds/application_base.html

`Submit for review` is the text used for all Funds and Labs and there is no way to define action text.

Remove unused variable in application_form.html

---

hypha/apply/funds/views.py

Do the set_status_after_reviewers_assigned for batch review update also.

---

hypha/static_src/src/javascript/apply/batch-actions.js

Fix for submission title in batch dialog.

---

README.md

Discussed with @saoun via email.

Replace me with Remote Inning in contributors

---

hypha/apply/funds/templates/funds/application_base_landing.html

Add the confirmation_text_extra to round landing page.

---

hypha/apply/funds/templates/funds/application_base.html

Fixes #1870 
I have added the deadline at the top of the application form. 
it might look like this.

Show deadline on application page

---

hypha/apply/funds/tables.py

Make the ninety_days column primary.

---

hypha/apply/funds/templates/funds/application_base.html
hypha/apply/stream_forms/templates/stream_forms/includes/file_field.html
hypha/apply/templates/forms/includes/field.html
hypha/static_src/src/javascript/apply/application-form-links-new-window.js

Add rel noopener noreferrer to all none local links with target blank.

---

.sass-lint.yml
hypha/static_src/src/app/src/components/DetailView/style.scss
hypha/static_src/src/app/src/components/Listing/style.scss
hypha/static_src/src/app/src/containers/DisplayPanel/style.scss
hypha/static_src/src/javascript/main-top.js
hypha/static_src/src/sass/apply/abstracts/_mixins.scss
hypha/static_src/src/sass/apply/components/_grid.scss
hypha/static_src/src/sass/public/components/_grid.scss
package.json

Remove fixes for Internet Explorer 11, very few users, if any, are using it still

---

hypha/apply/funds/models/mixins.py
hypha/apply/projects/models.py

Use legal name field if it exist to prefill Legal name on projects.

---

hypha/apply/funds/templates/funds/includes/revision_diff_table.html

Fixes https://github.com/OpenTechFund/issues.otf/issues/31

Fix ordering of required fields and use default datatime format.

---

.gitignore
docker/Dockerfile.dev
docker/docker-compose.yaml
hypha/settings/base.py
requirements.txt

Settings for Salesforce integration

---

hypha/apply/funds/tables.py
hypha/static_src/src/sass/apply/abstracts/_variables.scss
hypha/static_src/src/sass/apply/components/_form.scss
hypha/static_src/src/sass/apply/components/_select2.scss
hypha/static_src/src/sass/public/abstracts/_variables.scss
hypha/static_src/src/sass/public/components/_select2.scss

Add per page option to submission all list view filter.

---

hypha/apply/templates/forms/includes/field.html

Add conditional to add labels only when field is of type checkbox_input

---

hypha/apply/api/v1/review/views.py
hypha/apply/api/v1/stream_serializers.py
hypha/apply/api/v1/utils.py

Review api fix

---

hypha/cookieconsent/static/js/cookieconsent.js
hypha/cookieconsent/templates/includes/banner.html
hypha/static_src/src/sass/apply/components/_button.scss
hypha/static_src/src/sass/apply/components/_cookieconsent.scss
hypha/static_src/src/sass/apply/components/_wrapper.scss
hypha/static_src/src/sass/apply/main.scss
hypha/static_src/src/sass/public/components/_button.scss
hypha/static_src/src/sass/public/components/_cookieconsent.scss
hypha/static_src/src/sass/public/components/_wrapper.scss
hypha/static_src/src/sass/public/main.scss
hypha/templates/base-apply.html
hypha/templates/base.html

Fixes #ISSUEID
Add description here.

Moving cookie consent to bottom. Improving look and feel.

---

hypha/static_src/src/app/webpack.base.config.js
package-lock.json
package.json

Fixes #2122 
Replace deprecated @babel/polyfill with core-js

#2122 Replace @babel/polyfill with core-js

---

hypha/apply/funds/tests/test_views.py
hypha/apply/review/tests/test_views.py

Closes https://github.com/OpenTechFund/hypha/issues/2019

Add tests for review workflow

---

hypha/static_src/src/sass/apply/components/_form.scss
hypha/static_src/src/sass/public/components/_form.scss

Left align help links in application forms.

---

hypha/static_src/src/sass/apply/abstracts/_variables.scss
hypha/static_src/src/sass/apply/styleguide.scss
hypha/static_src/src/sass/public/abstracts/_variables.scss
hypha/static_src/src/sass/public/components/_button.scss
hypha/templates/styleguide.html

Extending the Hypha styleguide

---

hypha/static_src/src/javascript/public/dataviz-iframe.js

Fixing impacts-and-outcomes iframe js solution.

---

hypha/public/funds/templates/public_funds/fund_page.html
hypha/public/funds/templates/public_funds/lab_page.html
hypha/static_src/src/sass/public/components/_list_straight_left.scss
hypha/static_src/src/sass/public/components/_section.scss
hypha/static_src/src/sass/public/main.scss

Add list-straight-left styles to fund and lab pages.

---

hypha/apply/api/v1/filters.py
hypha/apply/api/v1/utils.py
hypha/apply/api/v1/views.py

Add code review changes of [PR 2184](https://github.com/OpenTechFund/hypha/pull/2184)

Code review changes of all submissions entry point in react app

---

hypha/static_src/src/app/src/components/SubmissionDisplay/index.js

Scroll to top while switching submissions
